--- 
javascripts: 
- base: 
  - prototype
  - FusionCharts
  - effects
  - dragdrop
  - controls
  - fast_autocompleter
  - application
stylesheets: 
- base: 
  - styles  
- printer:
    - printer-friendly
